name: cvd-prediction
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy>=1.21.0
  - pandas>=1.3.0
  - scikit-learn>=1.0.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - scipy>=1.7.0
  - joblib>=1.1.0
  - tqdm>=4.62.0
  - pyyaml>=6.0
  - jupyter
  - jupyterlab
  - ipywidgets
  - plotly>=5.0.0
  - pip:
    - tensorflow>=2.8.0
    - catboost>=1.0.0
    - xgboost>=1.5.0
    - shap>=0.40.0
    - pytest>=6.2.0
    - pytest-cov>=3.0.0
    - flake8>=4.0.0
    - black>=21.0.0
    - configparser>=5.2.0
    - pydicom>=2.2.0
    - nibabel>=3.2.0
    - statsmodels>=0.13.0
